#ifndef __CKMC_PLATFORM_CODES_H__
#define __CKMC_PLATFORM_CODES_H__

#include <errno.h>
#define TIZEN_ERROR_NONE 0
#define TIZEN_ERROR_INVALID_PARAMETER (-EINVAL)
#define TIZEN_ERROR_OUT_OF_MEMORY (-ENOMEM)
#define TIZEN_ERROR_PERMISSION_DENIED (-EACCES)
#define TIZEN_ERROR_NOT_SUPPORTED (-1073741824LL+2)
#define TIZEN_ERROR_KEY_MANAGER (-0x01E1000)

#endif

